[platformio]
default_envs = esp32c3

[env:esp32c3]
platform = espressif32@^6.5.0
board = esp32-c3-devkitm-1
framework = arduino

build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=3
    -DTESSORN_VERSION=\"1.2.0\"

lib_deps = 
    bblanchon/ArduinoJson@^7.0.4
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14
    fastled/FastLED@^3.6.0

board_build.filesystem = littlefs
board_build.partitions = default.csv

monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 921600

[env:esp32s3]
platform = espressif32@^6.5.0
board = esp32-s3-devkitc-1
framework = arduino
build_flags = ${env:esp32c3.build_flags}
lib_deps = ${env:esp32c3.lib_deps}
