#ifndef TESSORN_CONFIG_H
#define TESSORN_CONFIG_H

#define TESSORN_RUNTIME_VERSION "1.2.0"
#define PROTOCOL_VERSION "1.0.0"

#define MAX_GPIO_PINS 22
#define MAX_POWER_BUDGET_MA 500
#define POWER_SAFETY_MARGIN 0.8

#define MAX_BEHAVIORS 10
#define MAX_TRIGGERS_PER_BEHAVIOR 5
#define MAX_ACTIONS_PER_BEHAVIOR 10

#define SERIAL_BAUD_RATE 115200
#define COMMAND_TIMEOUT_MS 5000
#define HEARTBEAT_INTERVAL_MS 30000

#define BEHAVIOR_STORAGE_PATH "/behaviors"
#define MAX_STORED_BEHAVIORS 20

#define DEBUG_ENABLED true
#define DEBUG_SENSOR_DISCOVERY true

#endif
